name: Build and Push Docker Image

on:
  push:
    branches: 
      - master
      - development
      
jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker Courier image
        uses: docker/build-push-action@v3.0.0
        with:
          context: .
          file: ./Microservices/Courier-Management/dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/apps:${{ github.event.repository.name }}-${{ github.ref_name }}-courier-latest

          
      - name: Build and push Docker Delivery image
        uses: docker/build-push-action@v3.0.0
        with:
          context: .
          file: ./Microservices/Delivery-Tracking/dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/apps:${{ github.event.repository.name }}-${{ github.ref_name }}-delivery-latest
